### ISSUE TITLE
Deadlock error during generate catalog

### ISSUE THREAD

**Issue by tsing80** [rubenv/dupefinder#1]
The following error are shown when generate catalog (Running on Linux amd64 debian)

```
$dupefinder -generate dupefinder.cat /home/tsing80 /mnt/backup
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/rubenv/dupefinder.Generate(0x7ffca86d8342, 0xe, 0xc20800a030, 0x2, 0x2, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:56 +0x2ba
main.main()
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/bin/dupefinder/main.go:65 +0x5dc

goroutine 5 [chan send]:
github.com/rubenv/dupefinder.walkFolder(0xc208011a40, 0x70, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:194 +0x34c
github.com/rubenv/dupefinder.walkFolder(0xc2080362a0, 0x5c, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkFolder(0xc208036300, 0x58, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkFolder(0xc2080c6370, 0x50, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkFolder(0xc20807c940, 0x3a, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkFolder(0xc20803a4b0, 0x2f, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkFolder(0xc20801e120, 0x1e, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkFolder(0xc20801e220, 0x16, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkFolder(0x7ffca86d8351, 0xd, 0xc208036120, 0x0, 0x0)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:189 +0x268
github.com/rubenv/dupefinder.walkAllFolders(0xc2080360c0, 0xc208036120, 0xc20800a030, 0x2, 0x2)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:172 +0xda
created by github.com/rubenv/dupefinder.Generate
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:52 +0x254

goroutine 6 [semacquire, 11 minutes]:
sync.(*WaitGroup).Wait(0xc20801e020)
    /usr/local/go/src/sync/waitgroup.go:132 +0x169
github.com/rubenv/dupefinder.hashFiles(0xc2080360c0, 0xc208036120, 0xc208036180)
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:230 +0x1dc
created by github.com/rubenv/dupefinder.Generate
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:53 +0x282

goroutine 17 [chan send]:
github.com/rubenv/dupefinder.func·001()
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:218 +0x143
created by github.com/rubenv/dupefinder.hashFiles
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:227 +0x1af

goroutine 18 [chan send]:
github.com/rubenv/dupefinder.func·001()
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:218 +0x143
created by github.com/rubenv/dupefinder.hashFiles
    /home/tsing80/gocode/src/github.com/rubenv/dupefinder/dupefinder.go:227 +0x1af
```

**Comment by rubenv** [comment]
Can't seem to reproduce this. Which version of Go are you using?

**Comment by tsing80** [comment]
@rubenv: go 1.4

**Comment by rubenv** [comment]
I have no idea what is causing this. Since this appears to be in the folder walker, could you check:
- If there are any files/folders you don't have access to
- Are there any hardlinks in there?

**Comment by tsing80** [comment]
I can reproduce it by making 2 files in the directory that do not have read permission:

```
$ mkdir /tmp/test
$ touch /tmp/test/foo.txt
$ touch /tmp/test/bar.txt
$ chmod a-r /tmp/test/foo.txt
$ chmod a-r /tmp/test/bar.txt
$ dupefinder -generate dup.cat /tmp/test
```

The problem should be the main program is blocked when reading entries channel without reading err channel, the hashFiles block when putting the second error into the errs channel since the errs channel is full. This lead to deadlock

**Comment by rubenv** [comment]
Good catch. We should probably have a `select` in there.
